Refactoring
alercebroker/finding_chart_api pull request #5
Opened 2023-02-10 17:23 UTC by mcaceres2017

Refactoring done.

2023-02-10 17:54 UTC, dirodriguezm requested changes
La ruta base del paquete debería ser finding_chart o src, pero no finding_chart/src

2023-02-10 17:54 UTC, dirodriguezm commented on requirements.txt
> +gunicorn==20.1.0
Gunicorn no debería estar como dependencia acá. Solo van las dependencias de código. Las dependencias para crear la imagen se definen aparte, incluso en este caso bastaría con instalarlo en el Dockerfile

2023-02-10 17:54 UTC, dirodriguezm commented on Dockerfile
> -RUN pip install -r requirements.txt && pip install gunicorn>=20
Es mejor dejar la instalación de gunicorn en el Dockerfile, ya que en el requirements.txt van las dependencias de código.

2023-02-10 18:25 UTC, mcaceres2017 commented on requirements.txt
> +gunicorn==20.1.0
hecho

2023-02-10 18:25 UTC, mcaceres2017 commented on Dockerfile
> -RUN pip install -r requirements.txt && pip install gunicorn>=20
hecho

2023-02-15 17:39 UTC, dirodriguezm requested changes
En use_cases no veo los use_cases. Hay un archivo service.py que tiene (imagino) los casos de uso como métodos, pero no queda muy legible.

Mejor sería tener cada caso de uso por separado. Pero me queda la duda de cuantos casos de uso realmente hay acá. Me parace que debería haber un único caso de uso y ese caso de uso involucra llamar varios métodos de dominio. El service puede quedar como puerta de entrada a los métodos de dominio o bien los llama directamente el usecase.

El controller hace mucho trabajo actualmente. Debería ser una llamada al caso de uso y el formateo de input - output.

Un sketch básico de la arquitectura quedaría así
![image](https://user-images.githubusercontent.com/18015991/219109262-817fc032-fe09-43bb-bc23-d7245276a0fb.png)

2023-02-15 17:39 UTC, dirodriguezm commented on src/interface_adapters/controllers/controller.py
> +    size = request.args.get("size", default=1000)
Controller no debería usar request (objeto de fastapi). Podría hacer uso de un FastapiParser que pase los request a un DTO.

2023-02-15 18:13 UTC, mcaceres2017 commented on src/interface_adapters/controllers/controller.py
> +    size = request.args.get("size", default=1000)
lo tendre en cuenta pero eso lo arreglare en la rama fastAPI-view, esta rama solo la estamos usando para re-estructurar el codigo, y luego ir aplicando los cambios o actualizaciones en otras ramas.

2023-02-16 14:48 UTC, dirodriguezm requested changes

2023-02-16 14:48 UTC, dirodriguezm commented on src/entities/dtos.py
> +        self.size = size
Si este es un RequestDto, que se usa en la capa de UseCase debería ir junto al UseCase

2023-02-16 14:48 UTC, dirodriguezm commented on src/entities/dtos.py
> +        self.size = size
También me da la impresión que el object_repo debería ser un argumento adicional del UseCase y no parte del DTO. Igual que api o las demás dependencias.

2023-02-16 14:54 UTC, mcaceres2017 commented on src/entities/dtos.py
> +        self.size = size
en ese caso me queda la duda, ¿el objetivo de un dto no es encapsular toda la informacion posible para que, en caso de que haya que editar algo en el futuro, solo editar el dto?

2023-02-16 15:22 UTC, mcaceres2017 commented on src/entities/dtos.py
> +        self.size = size
cambio aplicado, ahora dto solo posee los atributos, oid y size

2023-02-16 17:17 UTC, dirodriguezm approved these changes

2023-02-16 17:20 UTC, merged